"""new fields in user model

Revision ID: 483e53bd1362
Revises: f3dd92ea1f40
Create Date: 2018-12-03 21:41:32.825498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483e53bd1362'
down_revision = 'f3dd92ea1f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
